spring:
  datasource:
    url: jdbc:mysql://localhost:13306/user_db
    username: root
    password: abc123
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns: com.atguigu.admin.*
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filters: stat,wall
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true

  jdbc:
    template:
      query-timeout: 3

#配置mybatis规则
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
#忽视命名驼峰规则
  configuration:
    map-underscore-to-camel-case: true
#spring.mvc.static-path-pattern=/static/**

